server:
  port: 8090
spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/customer?authSource=admin
#      username: root
#      password: 1234
#      host: localhost
#      port: 27017
#      database: customer
#      authentication-database: admin